---

language: python
python: "2.7"
install:
  - pip install ansible==1.5.0
script:
  - echo localhost > inventory

  # Syntax check
  - ansible-playbook -i inventory tests/test.yml --syntax-check

  # Play test
  - ansible-playbook -i inventory tests/test.yml --connection=local --sudo

  # Idempotence test
  - ansible-playbook -i inventory tests/test.yml --connection=local --sudo > idempotence_out
  - ./tests/idempotence_check.sh idempotence_out
